apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
     containers:
     - name: {.Values.name}
       image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
       ports:
       - containerPort: 5000

 
